name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  install:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 and install required dependencies + clone project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo apt update -y
            sudo apt install -y docker git
            sudo systemctl start docker
            sudo systemctl enable docker
            rm -rf learning-devops
            git clone https://github.com/AkshitVerma021/learning-devops.git
            cd learning-devops
            sudo docker system prune -a -f
            sudo docker build -t python .
            sudo docker run -d -p 5000:5000 --name python python
